### ISSUE TITLE
Pre-processing error attempting to run code on Windows 10

### ISSUE THREAD

**Issue by anikimmel** [QiujieDong/Laplacian2Mesh#6]
Hello!

I am trying to run the code that pre-processes the coseg_aliens dataset and coming up with this error message:

------generate vertices ground truth from edges------
data/coseg_aliens\train\1.obj
Traceback (most recent call last):
  File "./prepare/pre_seg_dataset.py", line 317, in <module>
    generate_vertices_ground_truth_from_edges(args)
  File "./prepare/pre_seg_dataset.py", line 211, in generate_vertices_ground_truth_from_edges
    meshcnn_mesh = Mesh(os.path.join(subset_mesh_path, file), opt)
  File "C:\Users\*****\PycharmProjects\Laplacian2Mesh\prepare\mesh.py", line 441, in __init__
    fill_mesh(self, file, opt)
  File "C:\Users\*****\PycharmProjects\Laplacian2Mesh\prepare\mesh.py", line 24, in fill_mesh
    mesh2fill.ve = mesh_data['ve']
  File "C:\Users\*****\AppData\Local\anaconda3\envs\L2M2\lib\site-packages\numpy\lib\npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 've is not a file in the archive'

Have you ever seen this before? It's just your vanilla code that is running, I have not made any modifications.

**Comment by QiujieDong** [comment]
@anikimmel 

sorry for the late reply!
I haven't encountered the issues you mentioned; we only run our code on Linux.
